version: 2.1
jobs:
  scan_ruby:
    docker:
      - image: cimg/ruby:3.0
        auth:
          username: wonderboooy
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: Scan for common Rails security vulnerabilities using static analysis
          command: |
            bin/brakeman --no-pager
  scan_js:
    docker:
      - image: cimg/node:17.2
        auth:
          username: wonderboooy
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: Scan for security vulnerabilities in JavaScript dependencies
          command: |
            bin/importmap audit
  lint:
    docker:
      - image: cimg/ruby:3.0
        auth:
          username: wonderboooy
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: Lint code for consistent style
          command: |
            bin/rubocop -f github

workflows:
  CI:
    jobs:
      - scan_ruby
      - scan_js
      - lint
